export interface Tool {
  slug: string;
  name: string;
  description: string;
  iconName: string;
  emoji: string;
  category: string;
  color: string;
  pro?: boolean;
  beta?: boolean;
  maxFilesMb?: number;
  accept?: string;
  multiple?: boolean;
  outputExt?: string;
}

export interface Category {
  id: string;
  label: string;
  color: string;
}

export const categories: Category[] = [
  { id: "convert-from", label: "Convert from PDF", color: "blue" },
  { id: "convert-to", label: "Convert to PDF", color: "violet" },
  { id: "organize", label: "Organize PDF", color: "green" },
  { id: "security", label: "PDF Security", color: "orange" },
  { id: "optimize", label: "Optimize & Repair", color: "yellow" },
  { id: "ocr", label: "OCR & Scan", color: "pink" },
  { id: "utility", label: "Utility", color: "cyan" },
];

const categoryTranslations: Record<string, Record<string, string>> = {
  "convert-from": {
    en: "Convert from PDF", ru: "Конвертация из PDF", de: "Von PDF konvertieren",
    fr: "Convertir depuis PDF", es: "Convertir de PDF", pt: "Converter de PDF",
    it: "Converti da PDF", zh: "从PDF转换", ja: "PDFから変換", ko: "PDF에서 변환",
    ar: "تحويل من PDF", tr: "PDF'den Dönüştür", hi: "PDF से कनवर्ट",
    pl: "Konwertuj z PDF", nl: "Van PDF converteren", uk: "Конвертація з PDF",
    vi: "Chuyển từ PDF", id: "Konversi dari PDF", th: "แปลงจาก PDF", cs: "Převést z PDF",
  },
  "convert-to": {
    en: "Convert to PDF", ru: "Конвертация в PDF", de: "In PDF konvertieren",
    fr: "Convertir en PDF", es: "Convertir a PDF", pt: "Converter para PDF",
    it: "Converti in PDF", zh: "转换为PDF", ja: "PDFに変換", ko: "PDF로 변환",
    ar: "تحويل إلى PDF", tr: "PDF'ye Dönüştür", hi: "PDF में कनवर्ट",
    pl: "Konwertuj do PDF", nl: "Naar PDF converteren", uk: "Конвертація в PDF",
    vi: "Chuyển sang PDF", id: "Konversi ke PDF", th: "แปลงเป็น PDF", cs: "Převést do PDF",
  },
  "organize": {
    en: "Organize PDF", ru: "Организация", de: "PDF organisieren",
    fr: "Organiser PDF", es: "Organizar PDF", pt: "Organizar PDF",
    it: "Organizza PDF", zh: "整理PDF", ja: "PDFを整理", ko: "PDF 정리",
    ar: "تنظيم PDF", tr: "PDF Düzenle", hi: "PDF व्यवस्थित",
    pl: "Organizuj PDF", nl: "PDF organiseren", uk: "Організація PDF",
    vi: "Tổ chức PDF", id: "Atur PDF", th: "จัดระเบียบ PDF", cs: "Uspořádat PDF",
  },
  "security": {
    en: "PDF Security", ru: "Безопасность", de: "PDF-Sicherheit",
    fr: "Sécurité PDF", es: "Seguridad PDF", pt: "Segurança PDF",
    it: "Sicurezza PDF", zh: "PDF安全", ja: "PDFセキュリティ", ko: "PDF 보안",
    ar: "أمان PDF", tr: "PDF Güvenliği", hi: "PDF सुरक्षा",
    pl: "Bezpieczeństwo PDF", nl: "PDF-beveiliging", uk: "Безпека PDF",
    vi: "Bảo mật PDF", id: "Keamanan PDF", th: "ความปลอดภัย PDF", cs: "Zabezpečení PDF",
  },
  "optimize": {
    en: "Optimize & Repair", ru: "Оптимизация", de: "Optimieren & Reparieren",
    fr: "Optimiser & Réparer", es: "Optimizar & Reparar", pt: "Otimizar & Reparar",
    it: "Ottimizza & Ripara", zh: "优化与修复", ja: "最適化・修復", ko: "최적화 및 복구",
    ar: "تحسين وإصلاح", tr: "Optimize Et & Onar", hi: "अनुकूलित करें",
    pl: "Optymalizuj & Napraw", nl: "Optimaliseren & Repareren", uk: "Оптимізація",
    vi: "Tối ưu hóa", id: "Optimalkan & Perbaiki", th: "ปรับปรุง & ซ่อม", cs: "Optimalizovat & Opravit",
  },
  "ocr": {
    en: "OCR & Scan", ru: "OCR и сканирование", de: "OCR & Scan",
    fr: "OCR & Scan", es: "OCR & Escaneo", pt: "OCR & Digitalizar",
    it: "OCR & Scansiona", zh: "OCR与扫描", ja: "OCR・スキャン", ko: "OCR 및 스캔",
    ar: "OCR ومسح", tr: "OCR ve Tarama", hi: "OCR और स्कैन",
    pl: "OCR & Skanowanie", nl: "OCR & Scannen", uk: "OCR та сканування",
    vi: "OCR & Quét", id: "OCR & Pindai", th: "OCR & สแกน", cs: "OCR & Skenovat",
  },
  "utility": {
    en: "Utility", ru: "Утилиты", de: "Dienstprogramme",
    fr: "Utilitaires", es: "Utilidades", pt: "Utilitários",
    it: "Utility", zh: "实用工具", ja: "ユーティリティ", ko: "유틸리티",
    ar: "أدوات", tr: "Araçlar", hi: "उपकरण",
    pl: "Narzędzia", nl: "Hulpprogramma's", uk: "Утиліти",
    vi: "Tiện ích", id: "Utilitas", th: "ยูทิลิตี้", cs: "Nástroje",
  },
};

export function getCategoryLabel(id: string, lang: string): string {
  return categoryTranslations[id]?.[lang] || categoryTranslations[id]?.en || id;
}

export const tools: Tool[] = [
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF files to editable Word documents with preserved formatting.",
    iconName: "FileText",
    emoji: "📄",
    category: "convert-from",
    color: "blue",
    accept: ".pdf",
    outputExt: "docx",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages to high-quality JPG images. Choose 72, 150 or 300 DPI.",
    iconName: "FileImage",
    emoji: "🖼️",
    category: "convert-from",
    color: "yellow",
    accept: ".pdf",
    outputExt: "jpg",
  },
  {
    slug: "pdf-to-png",
    name: "PDF to PNG",
    description: "Convert PDF pages to PNG images with transparency support.",
    iconName: "FileImage",
    emoji: "🏞️",
    category: "convert-from",
    color: "green",
    accept: ".pdf",
    outputExt: "png",
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract all text content from a PDF file quickly and cleanly.",
    iconName: "Type",
    emoji: "📝",
    category: "convert-from",
    color: "violet",
    accept: ".pdf",
    outputExt: "txt",
  },
  {
    slug: "pdf-to-html",
    name: "PDF to HTML",
    description: "Convert PDF documents to HTML format for web publishing.",
    iconName: "FileCode",
    emoji: "🌐",
    category: "convert-from",
    color: "sky",
    accept: ".pdf",
    outputExt: "html",
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract tables from PDF files into editable Excel spreadsheets.",
    iconName: "FileSpreadsheet",
    emoji: "📊",
    category: "convert-from",
    color: "red",
    accept: ".pdf",
    outputExt: "xlsx",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert Word documents (.docx) to PDF format instantly.",
    iconName: "FileText",
    emoji: "📑",
    category: "convert-to",
    color: "indigo",
    accept: ".docx",
    outputExt: "pdf",
  },
  {
    slug: "images-to-pdf",
    name: "Images to PDF",
    description: "Combine multiple JPG or PNG images into a single PDF file.",
    iconName: "FileImage",
    emoji: "🗃️",
    category: "convert-to",
    color: "orange",
    accept: ".jpg,.jpeg,.png",
    multiple: true,
    outputExt: "pdf",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert Excel spreadsheets to PDF documents.",
    iconName: "FileSpreadsheet",
    emoji: "📈",
    category: "convert-to",
    color: "rose",
    accept: ".xlsx,.xls",
    outputExt: "pdf",
  },
  {
    slug: "text-to-pdf",
    name: "Text to PDF",
    description: "Convert plain text files or pasted content into styled PDF documents.",
    iconName: "Type",
    emoji: "✏️",
    category: "convert-to",
    color: "amber",
    accept: ".txt",
    outputExt: "pdf",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one. Drag to reorder pages before merging.",
    iconName: "Merge",
    emoji: "🔗",
    category: "organize",
    color: "teal",
    accept: ".pdf",
    multiple: true,
    outputExt: "pdf",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Split a PDF by page ranges, every N pages, or extract specific pages.",
    iconName: "Scissors",
    emoji: "✂️",
    category: "organize",
    color: "red",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate pages in a PDF 90°, 180°, or 270° individually or all at once.",
    iconName: "RotateCw",
    emoji: "🔄",
    category: "organize",
    color: "blue",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "delete-pages",
    name: "Delete Pages",
    description: "Remove specific pages from a PDF by entering the page numbers to delete.",
    iconName: "Trash2",
    emoji: "🗑️",
    category: "organize",
    color: "cyan",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "reorder-pages",
    name: "Reorder Pages",
    description: "Rearrange PDF pages into any order by specifying a new page sequence.",
    iconName: "ArrowUpDown",
    emoji: "↕️",
    category: "organize",
    color: "violet",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "extract-pages",
    name: "Extract Pages",
    description: "Extract specific pages from a PDF into a new document.",
    iconName: "Download",
    emoji: "📤",
    category: "organize",
    color: "green",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Add password protection to your PDF files (server-side processing — coming to Pro).",
    iconName: "Lock",
    emoji: "🔐",
    category: "security",
    color: "orange",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password protection from PDF files you own.",
    iconName: "Unlock",
    emoji: "🔓",
    category: "security",
    color: "yellow",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Add a text signature to the last page of your PDF with custom color styling.",
    iconName: "PenLine",
    emoji: "✍️",
    category: "security",
    color: "amber",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "watermark-pdf",
    name: "Watermark PDF",
    description: "Add custom text or image watermarks with opacity and rotation controls.",
    iconName: "Droplets",
    emoji: "💧",
    category: "security",
    color: "sky",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    description: "Permanently black out sensitive content from your PDF documents.",
    iconName: "Shield",
    emoji: "⬛",
    category: "security",
    color: "rose",
    pro: true,
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size with 3 compression levels. See instant size reduction.",
    iconName: "Zap",
    emoji: "📦",
    category: "optimize",
    color: "green",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    description: "Attempt to fix corrupted or damaged PDF files automatically.",
    iconName: "Wrench",
    emoji: "🔧",
    category: "optimize",
    color: "yellow",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "flatten-pdf",
    name: "Flatten PDF",
    description: "Flatten form fields and annotations into the PDF content.",
    iconName: "Layers",
    emoji: "📋",
    category: "optimize",
    color: "orange",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "ocr-pdf",
    name: "OCR PDF",
    description: "Make scanned PDFs searchable using OCR. Supports 8 languages.",
    iconName: "ScanLine",
    emoji: "🔍",
    category: "ocr",
    color: "pink",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "photo-to-pdf",
    name: "Photo to PDF",
    description: "Capture from camera or upload photos, auto-crop and convert to clean PDF.",
    iconName: "Camera",
    emoji: "📷",
    category: "ocr",
    color: "orange",
    accept: ".jpg,.jpeg,.png,.webp",
    multiple: true,
    outputExt: "pdf",
  },
  {
    slug: "pdf-page-numbers",
    name: "Page Numbers",
    description: "Add page numbers to your PDF with custom position and format options.",
    iconName: "Hash",
    emoji: "🔢",
    category: "utility",
    color: "teal",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "pdf-header-footer",
    name: "Header & Footer",
    description: "Add custom headers and footers to every page of your PDF.",
    iconName: "AlignLeft",
    emoji: "📌",
    category: "utility",
    color: "indigo",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    description: "Add text, images, drawings and signatures to PDF pages directly in your browser.",
    iconName: "FileEdit",
    emoji: "✏️",
    category: "utility",
    color: "violet",
    accept: ".pdf",
    outputExt: "pdf",
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter((t) => t.category === categoryId);
}

export const categoryColors: Record<string, { bg: string; text: string; border: string; gradient: string; glow: string; from: string; to: string }> = {
  blue:    { bg: "bg-blue-500/10",    text: "text-blue-400",    border: "border-blue-500/20",    gradient: "rgba(59,130,246,0.18)",  glow: "rgba(59,130,246,0.25)",  from: "#3b82f6", to: "#2563eb" },
  violet:  { bg: "bg-violet-500/10",  text: "text-violet-400",  border: "border-violet-500/20",  gradient: "rgba(139,92,246,0.18)",  glow: "rgba(139,92,246,0.25)",  from: "#8b5cf6", to: "#7c3aed" },
  green:   { bg: "bg-emerald-500/10", text: "text-emerald-400", border: "border-emerald-500/20", gradient: "rgba(16,185,129,0.18)",  glow: "rgba(16,185,129,0.25)",  from: "#10b981", to: "#059669" },
  orange:  { bg: "bg-orange-500/10",  text: "text-orange-400",  border: "border-orange-500/20",  gradient: "rgba(249,115,22,0.18)",  glow: "rgba(249,115,22,0.25)",  from: "#f97316", to: "#ea580c" },
  yellow:  { bg: "bg-yellow-500/10",  text: "text-yellow-400",  border: "border-yellow-500/20",  gradient: "rgba(234,179,8,0.18)",   glow: "rgba(234,179,8,0.25)",   from: "#eab308", to: "#d97706" },
  pink:    { bg: "bg-pink-500/10",    text: "text-pink-400",    border: "border-pink-500/20",    gradient: "rgba(236,72,153,0.18)",  glow: "rgba(236,72,153,0.25)",  from: "#ec4899", to: "#db2777" },
  cyan:    { bg: "bg-cyan-500/10",    text: "text-cyan-400",    border: "border-cyan-500/20",    gradient: "rgba(6,182,212,0.18)",   glow: "rgba(6,182,212,0.25)",   from: "#06b6d4", to: "#0891b2" },
  red:     { bg: "bg-red-500/10",     text: "text-red-400",     border: "border-red-500/20",     gradient: "rgba(239,68,68,0.18)",   glow: "rgba(239,68,68,0.25)",   from: "#ef4444", to: "#dc2626" },
  teal:    { bg: "bg-teal-500/10",    text: "text-teal-400",    border: "border-teal-500/20",    gradient: "rgba(20,184,166,0.18)",  glow: "rgba(20,184,166,0.25)",  from: "#14b8a6", to: "#0d9488" },
  indigo:  { bg: "bg-indigo-500/10",  text: "text-indigo-400",  border: "border-indigo-500/20",  gradient: "rgba(99,102,241,0.18)",  glow: "rgba(99,102,241,0.25)",  from: "#6366f1", to: "#4f46e5" },
  amber:   { bg: "bg-amber-500/10",   text: "text-amber-400",   border: "border-amber-500/20",   gradient: "rgba(245,158,11,0.18)",  glow: "rgba(245,158,11,0.25)",  from: "#f59e0b", to: "#d97706" },
  rose:    { bg: "bg-rose-500/10",    text: "text-rose-400",    border: "border-rose-500/20",    gradient: "rgba(244,63,94,0.18)",   glow: "rgba(244,63,94,0.25)",   from: "#f43f5e", to: "#e11d48" },
  sky:     { bg: "bg-sky-500/10",     text: "text-sky-400",     border: "border-sky-500/20",     gradient: "rgba(14,165,233,0.18)",  glow: "rgba(14,165,233,0.25)",  from: "#0ea5e9", to: "#0284c7" },
};

