import type { LucideIcon } from "lucide-react";
import { FileText, FileImage, Layers, Scissors, RotateCw, Trash2, ArrowUpDown, Lock, Unlock, PenLine, Droplets, Zap, Wrench, ScanLine, Camera, Hash, AlignLeft, Shield, Merge, Download, FileCode, FileSpreadsheet, Type } from "lucide-react";

export interface Tool {
  slug: string;
  name: string;
  description: string;
  icon: LucideIcon;
  emoji: string;
  category: string;
  color: string;
  pro?: boolean;
  beta?: boolean;
  maxFilesMb?: number;
  accept?: string;
  multiple?: boolean;
  outputExt?: string;
}

export interface Category {
  id: string;
  label: string;
  color: string;
}

export const categories: Category[] = [
  { id: "convert-from", label: "Convert from PDF", color: "blue" },
  { id: "convert-to", label: "Convert to PDF", color: "violet" },
  { id: "organize", label: "Organize PDF", color: "green" },
  { id: "security", label: "PDF Security", color: "orange" },
  { id: "optimize", label: "Optimize & Repair", color: "yellow" },
  { id: "ocr", label: "OCR & Scan", color: "pink" },
  { id: "utility", label: "Utility", color: "cyan" },
];

const categoryTranslations: Record<string, Record<string, string>> = {
  "convert-from": {
    en: "Convert from PDF", ru: "Конвертация из PDF", de: "Von PDF konvertieren",
    fr: "Convertir depuis PDF", es: "Convertir de PDF", pt: "Converter de PDF",
    it: "Converti da PDF", zh: "从PDF转换", ja: "PDFから変換", ko: "PDF에서 변환",
    ar: "تحويل من PDF", tr: "PDF'den Dönüştür", hi: "PDF से कनवर्ट",
    pl: "Konwertuj z PDF", nl: "Van PDF converteren", uk: "Конвертація з PDF",
    vi: "Chuyển từ PDF", id: "Konversi dari PDF", th: "แปลงจาก PDF", cs: "Převést z PDF",
  },
  "convert-to": {
    en: "Convert to PDF", ru: "Конвертация в PDF", de: "In PDF konvertieren",
    fr: "Convertir en PDF", es: "Convertir a PDF", pt: "Converter para PDF",
    it: "Converti in PDF", zh: "转换为PDF", ja: "PDFに変換", ko: "PDF로 변환",
    ar: "تحويل إلى PDF", tr: "PDF'ye Dönüştür", hi: "PDF में कनवर्ट",
    pl: "Konwertuj do PDF", nl: "Naar PDF converteren", uk: "Конвертація в PDF",
    vi: "Chuyển sang PDF", id: "Konversi ke PDF", th: "แปลงเป็น PDF", cs: "Převést do PDF",
  },
  "organize": {
    en: "Organize PDF", ru: "Организация", de: "PDF organisieren",
    fr: "Organiser PDF", es: "Organizar PDF", pt: "Organizar PDF",
    it: "Organizza PDF", zh: "整理PDF", ja: "PDFを整理", ko: "PDF 정리",
    ar: "تنظيم PDF", tr: "PDF Düzenle", hi: "PDF व्यवस्थित",
    pl: "Organizuj PDF", nl: "PDF organiseren", uk: "Організація PDF",
    vi: "Tổ chức PDF", id: "Atur PDF", th: "จัดระเบียบ PDF", cs: "Uspořádat PDF",
  },
  "security": {
    en: "PDF Security", ru: "Безопасность", de: "PDF-Sicherheit",
    fr: "Sécurité PDF", es: "Seguridad PDF", pt: "Segurança PDF",
    it: "Sicurezza PDF", zh: "PDF安全", ja: "PDFセキュリティ", ko: "PDF 보안",
    ar: "أمان PDF", tr: "PDF Güvenliği", hi: "PDF सुरक्षा",
    pl: "Bezpieczeństwo PDF", nl: "PDF-beveiliging", uk: "Безпека PDF",
    vi: "Bảo mật PDF", id: "Keamanan PDF", th: "ความปลอดภัย PDF", cs: "Zabezpečení PDF",
  },
  "optimize": {
    en: "Optimize & Repair", ru: "Оптимизация", de: "Optimieren & Reparieren",
    fr: "Optimiser & Réparer", es: "Optimizar & Reparar", pt: "Otimizar & Reparar",
    it: "Ottimizza & Ripara", zh: "优化与修复", ja: "最適化・修復", ko: "최적화 및 복구",
    ar: "تحسين وإصلاح", tr: "Optimize Et & Onar", hi: "अनुकूलित करें",
    pl: "Optymalizuj & Napraw", nl: "Optimaliseren & Repareren", uk: "Оптимізація",
    vi: "Tối ưu hóa", id: "Optimalkan & Perbaiki", th: "ปรับปรุง & ซ่อม", cs: "Optimalizovat & Opravit",
  },
  "ocr": {
    en: "OCR & Scan", ru: "OCR и сканирование", de: "OCR & Scan",
    fr: "OCR & Scan", es: "OCR & Escaneo", pt: "OCR & Digitalizar",
    it: "OCR & Scansiona", zh: "OCR与扫描", ja: "OCR・スキャン", ko: "OCR 및 스캔",
    ar: "OCR ومسح", tr: "OCR ve Tarama", hi: "OCR और स्कैन",
    pl: "OCR & Skanowanie", nl: "OCR & Scannen", uk: "OCR та сканування",
    vi: "OCR & Quét", id: "OCR & Pindai", th: "OCR & สแกน", cs: "OCR & Skenovat",
  },
  "utility": {
    en: "Utility", ru: "Утилиты", de: "Dienstprogramme",
    fr: "Utilitaires", es: "Utilidades", pt: "Utilitários",
    it: "Utility", zh: "实用工具", ja: "ユーティリティ", ko: "유틸리티",
    ar: "أدوات", tr: "Araçlar", hi: "उपकरण",
    pl: "Narzędzia", nl: "Hulpprogramma's", uk: "Утиліти",
    vi: "Tiện ích", id: "Utilitas", th: "ยูทิลิตี้", cs: "Nástroje",
  },
};

export function getCategoryLabel(id: string, lang: string): string {
  return categoryTranslations[id]?.[lang] || categoryTranslations[id]?.en || id;
}

export const tools: Tool[] = [
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF files to editable Word documents with preserved formatting.",
    icon: FileText,
    emoji: "📄",
    category: "convert-from",
    color: "blue",
    accept: ".pdf",
    outputExt: "docx",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages to high-quality JPG images. Choose 72, 150 or 300 DPI.",
    icon: FileImage,
    emoji: "🖼️",
    category: "convert-from",
    color: "blue",
    accept: ".pdf",
    outputExt: "jpg",
  },
  {
    slug: "pdf-to-png",
    name: "PDF to PNG",
    description: "Convert PDF pages to PNG images with transparency support.",
    icon: FileImage,
    emoji: "🏞️",
    category: "convert-from",
    color: "blue",
    accept: ".pdf",
    outputExt: "png",
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract all text content from a PDF file quickly and cleanly.",
    icon: Type,
    emoji: "📝",
    category: "convert-from",
    color: "blue",
    accept: ".pdf",
    outputExt: "txt",
  },
  {
    slug: "pdf-to-html",
    name: "PDF to HTML",
    description: "Convert PDF documents to HTML format for web publishing.",
    icon: FileCode,
    emoji: "🌐",
    category: "convert-from",
    color: "blue",
    accept: ".pdf",
    outputExt: "html",
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract tables from PDF files into editable Excel spreadsheets.",
    icon: FileSpreadsheet,
    emoji: "📊",
    category: "convert-from",
    color: "blue",
    accept: ".pdf",
    outputExt: "xlsx",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert Word documents (.docx) to PDF format instantly.",
    icon: FileText,
    emoji: "📑",
    category: "convert-to",
    color: "violet",
    accept: ".docx,.doc",
    outputExt: "pdf",
  },
  {
    slug: "images-to-pdf",
    name: "Images to PDF",
    description: "Combine multiple JPG or PNG images into a single PDF file.",
    icon: FileImage,
    emoji: "🗃️",
    category: "convert-to",
    color: "violet",
    accept: ".jpg,.jpeg,.png,.webp",
    multiple: true,
    outputExt: "pdf",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert Excel spreadsheets to PDF documents.",
    icon: FileSpreadsheet,
    emoji: "📈",
    category: "convert-to",
    color: "violet",
    accept: ".xlsx,.xls",
    outputExt: "pdf",
  },
  {
    slug: "text-to-pdf",
    name: "Text to PDF",
    description: "Convert plain text files or pasted content into styled PDF documents.",
    icon: Type,
    emoji: "✏️",
    category: "convert-to",
    color: "violet",
    accept: ".txt",
    outputExt: "pdf",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one. Drag to reorder pages before merging.",
    icon: Merge,
    emoji: "🔗",
    category: "organize",
    color: "green",
    accept: ".pdf",
    multiple: true,
    outputExt: "pdf",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Split a PDF by page ranges, every N pages, or extract specific pages.",
    icon: Scissors,
    emoji: "✂️",
    category: "organize",
    color: "green",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate pages in a PDF 90°, 180°, or 270° individually or all at once.",
    icon: RotateCw,
    emoji: "🔄",
    category: "organize",
    color: "green",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "delete-pages",
    name: "Delete Pages",
    description: "Remove specific pages from a PDF using a visual page selector.",
    icon: Trash2,
    emoji: "🗑️",
    category: "organize",
    color: "green",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "reorder-pages",
    name: "Reorder Pages",
    description: "Drag and drop PDF pages into any order you need.",
    icon: ArrowUpDown,
    emoji: "↕️",
    category: "organize",
    color: "green",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "extract-pages",
    name: "Extract Pages",
    description: "Extract specific pages from a PDF into a new document.",
    icon: Download,
    emoji: "📤",
    category: "organize",
    color: "green",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Add AES-256 password encryption to protect your PDF files.",
    icon: Lock,
    emoji: "🔐",
    category: "security",
    color: "orange",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password protection from PDF files you own.",
    icon: Unlock,
    emoji: "🔓",
    category: "security",
    color: "orange",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Draw your signature or upload an image and place it on your PDF.",
    icon: PenLine,
    emoji: "✍️",
    category: "security",
    color: "orange",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "watermark-pdf",
    name: "Watermark PDF",
    description: "Add custom text or image watermarks with opacity and rotation controls.",
    icon: Droplets,
    emoji: "💧",
    category: "security",
    color: "orange",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    description: "Permanently black out sensitive content from your PDF documents.",
    icon: Shield,
    emoji: "⬛",
    category: "security",
    color: "orange",
    pro: true,
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size with 3 compression levels. See instant size reduction.",
    icon: Zap,
    emoji: "📦",
    category: "optimize",
    color: "yellow",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    description: "Attempt to fix corrupted or damaged PDF files automatically.",
    icon: Wrench,
    emoji: "🔧",
    category: "optimize",
    color: "yellow",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "flatten-pdf",
    name: "Flatten PDF",
    description: "Flatten form fields and annotations into the PDF content.",
    icon: Layers,
    emoji: "📋",
    category: "optimize",
    color: "yellow",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "ocr-pdf",
    name: "OCR PDF",
    description: "Make scanned PDFs searchable using OCR. Supports 8 languages.",
    icon: ScanLine,
    emoji: "🔍",
    category: "ocr",
    color: "pink",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "photo-to-pdf",
    name: "Photo to PDF",
    description: "Capture from camera or upload photos, auto-crop and convert to clean PDF.",
    icon: Camera,
    emoji: "📷",
    category: "ocr",
    color: "pink",
    accept: ".jpg,.jpeg,.png,.webp",
    multiple: true,
    outputExt: "pdf",
  },
  {
    slug: "pdf-page-numbers",
    name: "Page Numbers",
    description: "Add page numbers to your PDF with custom position and format options.",
    icon: Hash,
    emoji: "🔢",
    category: "utility",
    color: "cyan",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "pdf-header-footer",
    name: "Header & Footer",
    description: "Add custom headers and footers to every page of your PDF.",
    icon: AlignLeft,
    emoji: "📌",
    category: "utility",
    color: "cyan",
    accept: ".pdf",
    outputExt: "pdf",
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter((t) => t.category === categoryId);
}

export const categoryColors: Record<string, { bg: string; text: string; border: string; gradient: string; glow: string }> = {
  blue: { bg: "bg-blue-500/10", text: "text-blue-400", border: "border-blue-500/20", gradient: "rgba(59,130,246,0.18)", glow: "rgba(59,130,246,0.25)" },
  violet: { bg: "bg-violet-500/10", text: "text-violet-400", border: "border-violet-500/20", gradient: "rgba(139,92,246,0.18)", glow: "rgba(139,92,246,0.25)" },
  green: { bg: "bg-emerald-500/10", text: "text-emerald-400", border: "border-emerald-500/20", gradient: "rgba(16,185,129,0.18)", glow: "rgba(16,185,129,0.25)" },
  orange: { bg: "bg-orange-500/10", text: "text-orange-400", border: "border-orange-500/20", gradient: "rgba(249,115,22,0.18)", glow: "rgba(249,115,22,0.25)" },
  yellow: { bg: "bg-yellow-500/10", text: "text-yellow-400", border: "border-yellow-500/20", gradient: "rgba(234,179,8,0.18)", glow: "rgba(234,179,8,0.25)" },
  pink: { bg: "bg-pink-500/10", text: "text-pink-400", border: "border-pink-500/20", gradient: "rgba(236,72,153,0.18)", glow: "rgba(236,72,153,0.25)" },
  cyan: { bg: "bg-cyan-500/10", text: "text-cyan-400", border: "border-cyan-500/20", gradient: "rgba(6,182,212,0.18)", glow: "rgba(6,182,212,0.25)" },
};
