import type { LucideIcon } from "lucide-react";
import { FileText, FileImage, Layers, Scissors, RotateCw, Trash2, ArrowUpDown, Lock, Unlock, PenLine, Droplets, Zap, Wrench, ScanLine, Camera, Hash, AlignLeft, Shield, Merge, Download, FileCode, FileSpreadsheet, Type, FileEdit, Crop, ImageDown, Tag, SplitSquareHorizontal, FileX, Maximize2, Contrast, BookMarked, FlipHorizontal, GitCompare, Regex, Minimize2, Sun, ImageOff, ClipboardList, BookOpen, BookCopy, Wand2, PaintBucket, Volume2 } from "lucide-react";

export interface Tool {
  slug: string;
  name: string;
  description: string;
  icon: LucideIcon;
  emoji: string;
  category: string;
  color: string;
  pro?: boolean;
  beta?: boolean;
  maxFilesMb?: number;
  accept?: string;
  multiple?: boolean;
  outputExt?: string;
}

export interface Category {
  id: string;
  label: string;
  color: string;
}

export const categories: Category[] = [
  { id: "convert-from", label: "Convert from PDF", color: "blue" },
  { id: "convert-to", label: "Convert to PDF", color: "violet" },
  { id: "organize", label: "Organize PDF", color: "green" },
  { id: "security", label: "PDF Security", color: "orange" },
  { id: "optimize", label: "Optimize & Repair", color: "yellow" },
  { id: "ocr", label: "OCR & Scan", color: "pink" },
  { id: "utility", label: "Utility", color: "cyan" },
];

const categoryTranslations: Record<string, Record<string, string>> = {
  "convert-from": {
    en: "Convert from PDF", ru: "Конвертация из PDF", de: "Von PDF konvertieren",
    fr: "Convertir depuis PDF", es: "Convertir de PDF", pt: "Converter de PDF",
    it: "Converti da PDF", zh: "从PDF转换", ja: "PDFから変換", ko: "PDF에서 변환",
    ar: "تحويل من PDF", tr: "PDF'den Dönüştür", hi: "PDF से कनवर्ट",
    pl: "Konwertuj z PDF", nl: "Van PDF converteren", uk: "Конвертація з PDF",
    vi: "Chuyển từ PDF", id: "Konversi dari PDF", th: "แปลงจาก PDF", cs: "Převést z PDF",
  },
  "convert-to": {
    en: "Convert to PDF", ru: "Конвертация в PDF", de: "In PDF konvertieren",
    fr: "Convertir en PDF", es: "Convertir a PDF", pt: "Converter para PDF",
    it: "Converti in PDF", zh: "转换为PDF", ja: "PDFに変換", ko: "PDF로 변환",
    ar: "تحويل إلى PDF", tr: "PDF'ye Dönüştür", hi: "PDF में कनवर्ट",
    pl: "Konwertuj do PDF", nl: "Naar PDF converteren", uk: "Конвертація в PDF",
    vi: "Chuyển sang PDF", id: "Konversi ke PDF", th: "แปลงเป็น PDF", cs: "Převést do PDF",
  },
  "organize": {
    en: "Organize PDF", ru: "Организация", de: "PDF organisieren",
    fr: "Organiser PDF", es: "Organizar PDF", pt: "Organizar PDF",
    it: "Organizza PDF", zh: "整理PDF", ja: "PDFを整理", ko: "PDF 정리",
    ar: "تنظيم PDF", tr: "PDF Düzenle", hi: "PDF व्यवस्थित",
    pl: "Organizuj PDF", nl: "PDF organiseren", uk: "Організація PDF",
    vi: "Tổ chức PDF", id: "Atur PDF", th: "จัดระเบียบ PDF", cs: "Uspořádat PDF",
  },
  "security": {
    en: "PDF Security", ru: "Безопасность", de: "PDF-Sicherheit",
    fr: "Sécurité PDF", es: "Seguridad PDF", pt: "Segurança PDF",
    it: "Sicurezza PDF", zh: "PDF安全", ja: "PDFセキュリティ", ko: "PDF 보안",
    ar: "أمان PDF", tr: "PDF Güvenliği", hi: "PDF सुरक्षा",
    pl: "Bezpieczeństwo PDF", nl: "PDF-beveiliging", uk: "Безпека PDF",
    vi: "Bảo mật PDF", id: "Keamanan PDF", th: "ความปลอดภัย PDF", cs: "Zabezpečení PDF",
  },
  "optimize": {
    en: "Optimize & Repair", ru: "Оптимизация", de: "Optimieren & Reparieren",
    fr: "Optimiser & Réparer", es: "Optimizar & Reparar", pt: "Otimizar & Reparar",
    it: "Ottimizza & Ripara", zh: "优化与修复", ja: "最適化・修復", ko: "최적화 및 복구",
    ar: "تحسين وإصلاح", tr: "Optimize Et & Onar", hi: "अनुकूलित करें",
    pl: "Optymalizuj & Napraw", nl: "Optimaliseren & Repareren", uk: "Оптимізація",
    vi: "Tối ưu hóa", id: "Optimalkan & Perbaiki", th: "ปรับปรุง & ซ่อม", cs: "Optimalizovat & Opravit",
  },
  "ocr": {
    en: "OCR & Scan", ru: "OCR и сканирование", de: "OCR & Scan",
    fr: "OCR & Scan", es: "OCR & Escaneo", pt: "OCR & Digitalizar",
    it: "OCR & Scansiona", zh: "OCR与扫描", ja: "OCR・スキャン", ko: "OCR 및 스캔",
    ar: "OCR ومسح", tr: "OCR ve Tarama", hi: "OCR और स्कैन",
    pl: "OCR & Skanowanie", nl: "OCR & Scannen", uk: "OCR та сканування",
    vi: "OCR & Quét", id: "OCR & Pindai", th: "OCR & สแกน", cs: "OCR & Skenovat",
  },
  "utility": {
    en: "Utility", ru: "Утилиты", de: "Dienstprogramme",
    fr: "Utilitaires", es: "Utilidades", pt: "Utilitários",
    it: "Utility", zh: "实用工具", ja: "ユーティリティ", ko: "유틸리티",
    ar: "أدوات", tr: "Araçlar", hi: "उपकरण",
    pl: "Narzędzia", nl: "Hulpprogramma's", uk: "Утиліти",
    vi: "Tiện ích", id: "Utilitas", th: "ยูทิลิตี้", cs: "Nástroje",
  },
};

export function getCategoryLabel(id: string, lang: string): string {
  return categoryTranslations[id]?.[lang] || categoryTranslations[id]?.en || id;
}

export const tools: Tool[] = [
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Extract text from a PDF into an editable Word (.docx) document.",
    icon: FileText,
    emoji: "📄",
    category: "convert-from",
    color: "blue",
    accept: ".pdf",
    outputExt: "docx",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages to high-quality JPG images. Choose standard, high or maximum quality.",
    icon: FileImage,
    emoji: "🖼️",
    category: "convert-from",
    color: "yellow",
    accept: ".pdf",
    outputExt: "jpg",
  },
  {
    slug: "pdf-to-png",
    name: "PDF to PNG",
    description: "Convert PDF pages to high-quality PNG images.",
    icon: FileImage,
    emoji: "🏞️",
    category: "convert-from",
    color: "green",
    accept: ".pdf",
    outputExt: "png",
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract all text content from a PDF file quickly and cleanly.",
    icon: Type,
    emoji: "📝",
    category: "convert-from",
    color: "violet",
    accept: ".pdf",
    outputExt: "txt",
  },
  {
    slug: "pdf-to-html",
    name: "PDF to HTML",
    description: "Convert PDF documents to HTML format for web publishing.",
    icon: FileCode,
    emoji: "🌐",
    category: "convert-from",
    color: "sky",
    accept: ".pdf",
    outputExt: "html",
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract tables from PDF files into editable Excel spreadsheets.",
    icon: FileSpreadsheet,
    emoji: "📊",
    category: "convert-from",
    color: "red",
    accept: ".pdf",
    outputExt: "xlsx",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert Word documents (.docx) to PDF format instantly.",
    icon: FileText,
    emoji: "📑",
    category: "convert-to",
    color: "indigo",
    accept: ".docx",
    outputExt: "pdf",
  },
  {
    slug: "images-to-pdf",
    name: "Images to PDF",
    description: "Combine multiple JPG or PNG images into a single PDF file.",
    icon: FileImage,
    emoji: "🗃️",
    category: "convert-to",
    color: "orange",
    accept: ".jpg,.jpeg,.png",
    multiple: true,
    outputExt: "pdf",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert Excel spreadsheets to PDF documents.",
    icon: FileSpreadsheet,
    emoji: "📈",
    category: "convert-to",
    color: "rose",
    accept: ".xlsx,.xls",
    outputExt: "pdf",
  },
  {
    slug: "text-to-pdf",
    name: "Text to PDF",
    description: "Convert plain text files or pasted content into styled PDF documents.",
    icon: Type,
    emoji: "✏️",
    category: "convert-to",
    color: "amber",
    accept: ".txt",
    outputExt: "pdf",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one. Drag to reorder pages before merging.",
    icon: Merge,
    emoji: "🔗",
    category: "organize",
    color: "teal",
    accept: ".pdf",
    multiple: true,
    outputExt: "pdf",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Split a PDF by page ranges, every N pages, or extract specific pages.",
    icon: Scissors,
    emoji: "✂️",
    category: "organize",
    color: "red",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate pages in a PDF 90°, 180°, or 270° individually or all at once.",
    icon: RotateCw,
    emoji: "🔄",
    category: "organize",
    color: "blue",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "delete-pages",
    name: "Delete Pages",
    description: "Remove specific pages from a PDF by entering the page numbers to delete.",
    icon: Trash2,
    emoji: "🗑️",
    category: "organize",
    color: "cyan",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "reorder-pages",
    name: "Reorder Pages",
    description: "Rearrange PDF pages into any order by specifying a new page sequence.",
    icon: ArrowUpDown,
    emoji: "↕️",
    category: "organize",
    color: "violet",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "extract-pages",
    name: "Extract Pages",
    description: "Extract specific pages from a PDF into a new document.",
    icon: Download,
    emoji: "📤",
    category: "organize",
    color: "green",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Add AES-256 password protection to your PDF files.",
    icon: Lock,
    emoji: "🔐",
    category: "security",
    color: "orange",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password protection from PDF files you own.",
    icon: Unlock,
    emoji: "🔓",
    category: "security",
    color: "yellow",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Add a text signature to the last page of your PDF with custom color styling.",
    icon: PenLine,
    emoji: "✍️",
    category: "security",
    color: "amber",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "watermark-pdf",
    name: "Watermark PDF",
    description: "Add custom text watermarks with opacity and rotation controls.",
    icon: Droplets,
    emoji: "💧",
    category: "security",
    color: "sky",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    description: "Permanently black out sensitive content from your PDF documents.",
    icon: Shield,
    emoji: "⬛",
    category: "security",
    color: "rose",
    pro: true,
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Optimize the PDF structure to reduce file size. Returns the original if it can't be reduced.",
    icon: Zap,
    emoji: "📦",
    category: "optimize",
    color: "green",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "ocr-pdf",
    name: "OCR PDF",
    description: "Make scanned PDFs searchable using OCR. Supports 8 languages.",
    icon: ScanLine,
    emoji: "🔍",
    category: "ocr",
    color: "pink",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "photo-to-pdf",
    name: "Photo to PDF",
    description: "Upload photos (JPG/PNG) and convert them into a clean PDF.",
    icon: Camera,
    emoji: "📷",
    category: "ocr",
    color: "orange",
    accept: ".jpg,.jpeg,.png,.webp",
    multiple: true,
    outputExt: "pdf",
  },
  {
    slug: "pdf-page-numbers",
    name: "Page Numbers",
    description: "Add page numbers to your PDF with custom position and format options.",
    icon: Hash,
    emoji: "🔢",
    category: "utility",
    color: "teal",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "pdf-header-footer",
    name: "Header & Footer",
    description: "Add custom headers and footers to every page of your PDF.",
    icon: AlignLeft,
    emoji: "📌",
    category: "utility",
    color: "indigo",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "bates-numbering",
    name: "Bates Numbering",
    description: "Stamp sequential Bates identifiers (e.g. CASE-000001) on every page for legal documents.",
    icon: ClipboardList,
    emoji: "🔢",
    category: "utility",
    color: "slate",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    description: "Add text, images, drawings and signatures to PDF pages directly in your browser.",
    icon: FileEdit,
    emoji: "✏️",
    category: "utility",
    color: "violet",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "crop-pdf",
    name: "Crop PDF",
    description: "Trim margins from PDF pages by setting custom crop values for all sides.",
    icon: Crop,
    emoji: "✂️",
    category: "organize",
    color: "teal",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "extract-images",
    name: "Extract Images",
    description: "Extract all images from a PDF file and download them as a ZIP archive.",
    icon: ImageDown,
    emoji: "🖼️",
    category: "convert-from",
    color: "pink",
    accept: ".pdf",
    outputExt: "zip",
  },
  {
    slug: "pdf-metadata",
    name: "PDF Metadata",
    description: "View and edit PDF metadata: title, author, subject, keywords, and creation date.",
    icon: Tag,
    emoji: "🏷️",
    category: "utility",
    color: "amber",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "compare-pdf",
    name: "Compare PDF",
    description: "Compare two PDF files side by side to spot differences between versions.",
    icon: SplitSquareHorizontal,
    emoji: "🔀",
    category: "utility",
    color: "sky",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "remove-blank-pages",
    name: "Remove Blank Pages",
    description: "Automatically detect and remove blank or near-blank pages from your PDF.",
    icon: FileX,
    emoji: "🗑️",
    category: "organize",
    color: "rose",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "resize-pages",
    name: "Resize Pages",
    description: "Resize or scale all PDF pages to a standard size: A4, A3, Letter, and more.",
    icon: Maximize2,
    emoji: "📐",
    category: "organize",
    color: "indigo",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "grayscale-pdf",
    name: "Grayscale PDF",
    description: "Convert a color PDF to grayscale for printing or archiving.",
    icon: Contrast,
    emoji: "🔲",
    category: "utility",
    color: "slate",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "pdf-bookmarks",
    name: "PDF Bookmarks",
    description: "View and export the table of contents and bookmarks from any PDF.",
    icon: BookMarked,
    emoji: "📑",
    category: "utility",
    color: "green",
    accept: ".pdf",
    outputExt: "txt",
  },
  {
    slug: "sanitize-pdf",
    name: "Sanitize PDF",
    description: "Remove metadata, JavaScript, and tracking from your PDF for privacy.",
    icon: Shield,
    emoji: "🛡️",
    category: "security",
    color: "orange",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "extract-forms",
    name: "Extract Form Fields",
    description: "Extract form field data from PDF to JSON format.",
    icon: FileCode,
    emoji: "📋",
    category: "utility",
    color: "cyan",
    accept: ".pdf",
    outputExt: "json",
  },
  {
    slug: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    description: "Convert PDF to archival PDF/A format for long-term storage.",
    icon: FileText,
    emoji: "📦",
    category: "convert-from",
    color: "blue",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "add-blank-pages",
    name: "Add Blank Pages",
    description: "Insert blank pages at specified positions in your PDF.",
    icon: FileText,
    emoji: "📄",
    category: "organize",
    color: "indigo",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    description: "Attempt to repair and recover a corrupted or damaged PDF file.",
    icon: Wrench,
    emoji: "🔧",
    category: "utility",
    color: "slate",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "flatten-pdf",
    name: "Flatten PDF",
    description: "Flatten interactive form fields into static text, making the PDF non-editable.",
    icon: Minimize2,
    emoji: "📋",
    category: "utility",
    color: "teal",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "auto-redact",
    name: "Auto Redact",
    description: "Automatically detect and redact emails, phone numbers, or custom patterns from PDF text.",
    icon: Regex,
    emoji: "🔴",
    category: "security",
    color: "rose",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "n-up-pdf",
    name: "N-Up PDF",
    description: "Arrange multiple PDF pages per sheet (2-up, 4-up) for compact printing.",
    icon: Layers,
    emoji: "📄",
    category: "organize",
    color: "indigo",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "split-by-size",
    name: "Split by Size",
    description: "Split a large PDF into smaller files, each under a maximum file size.",
    icon: Scissors,
    emoji: "✂️",
    category: "organize",
    color: "orange",
    accept: ".pdf",
    outputExt: "zip",
  },
  {
    slug: "overlay-pdf",
    name: "Overlay PDF",
    description: "Overlay one PDF on top of another — use as a PDF-based watermark or template.",
    icon: FlipHorizontal,
    emoji: "🖼️",
    category: "utility",
    color: "violet",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "invert-colors",
    name: "Invert Colors",
    description: "Invert PDF colors to create a dark-mode version or reduce eye strain when reading.",
    icon: Sun,
    emoji: "🌙",
    category: "utility",
    color: "slate",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "to-single-page",
    name: "To Single Page",
    description: "Combine all PDF pages into one long continuous page — ideal for web or scrollable documents.",
    icon: Minimize2,
    emoji: "📜",
    category: "organize",
    color: "teal",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "remove-images",
    name: "Remove Images",
    description: "Strip all images from a PDF while keeping text and vector content intact.",
    icon: ImageOff,
    emoji: "🚫",
    category: "utility",
    color: "rose",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "form-fill",
    name: "Fill PDF Form",
    description: "Fill in PDF form fields interactively and download the completed document.",
    icon: ClipboardList,
    emoji: "📝",
    category: "utility",
    color: "blue",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "split-by-chapters",
    name: "Split by Chapters",
    description: "Split a PDF into separate files based on its bookmarks and chapter structure.",
    icon: BookOpen,
    emoji: "📖",
    category: "organize",
    color: "amber",
    accept: ".pdf",
    outputExt: "zip",
  },
  {
    slug: "booklet-imposition",
    name: "Booklet",
    description: "Rearrange PDF pages for booklet printing — fold and staple to create a booklet.",
    icon: BookCopy,
    emoji: "📚",
    category: "organize",
    color: "indigo",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "scanner-effect",
    name: "Scanner Effect",
    description: "Apply a scanned document look with paper texture, slight rotation, and aged yellowing.",
    icon: Wand2,
    emoji: "📷",
    category: "utility",
    color: "orange",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "pdf-to-markdown",
    name: "PDF to Markdown",
    description: "Extract text content from PDF and convert to Markdown format with headings and structure.",
    icon: FileText,
    emoji: "📝",
    category: "convert-from",
    color: "green",
    accept: ".pdf",
    outputExt: "md",
  },
  {
    slug: "add-background",
    name: "Add Background",
    description: "Add a colored or semi-transparent background to all PDF pages.",
    icon: PaintBucket,
    emoji: "🎨",
    category: "utility",
    color: "pink",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "pdf-diff",
    name: "PDF Diff",
    description: "Highlight differences between two PDF documents with colored markers.",
    icon: GitCompare,
    emoji: "🔍",
    category: "utility",
    color: "red",
    accept: ".pdf",
    outputExt: "pdf",
  },
  {
    slug: "pdf-to-audio",
    name: "PDF to Audio",
    description: "Read PDF text aloud using text-to-speech in your browser.",
    icon: Volume2,
    emoji: "🔊",
    category: "convert-from",
    color: "blue",
    accept: ".pdf",
    outputExt: "audio",
  },
  {
    slug: "pdf-to-pptx",
    name: "PDF to PowerPoint",
    description: "Convert each PDF page into a PowerPoint slide with high-quality images.",
    icon: FileCode,
    emoji: "📊",
    category: "convert-from",
    color: "orange",
    accept: ".pdf",
    outputExt: "pptx",
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter((t) => t.category === categoryId);
}

export const ROADMAP_TOOL_SLUGS = new Set<string>();

export function isToolLaunchReady(toolOrSlug: Tool | string): boolean {
  const slug = typeof toolOrSlug === "string" ? toolOrSlug : toolOrSlug.slug;
  return !ROADMAP_TOOL_SLUGS.has(slug);
}

export function getLaunchReadyTools(): Tool[] {
  return tools.filter((tool) => isToolLaunchReady(tool));
}

export function getRoadmapTools(): Tool[] {
  return tools.filter((tool) => !isToolLaunchReady(tool));
}

// Curated list of the most-used PDF tools, ordered by typical popularity.
// Drives the "Popular" section shown first on the home page.
export const POPULAR_TOOL_SLUGS: string[] = [
  "merge-pdf",
  "split-pdf",
  "compress-pdf",
  "pdf-to-word",
  "word-to-pdf",
  "pdf-to-jpg",
  "images-to-pdf",
  "edit-pdf",
  "sign-pdf",
  "protect-pdf",
];

export function getPopularTools(limit = 10): Tool[] {
  return POPULAR_TOOL_SLUGS.map((slug) => getToolBySlug(slug))
    .filter((tool): tool is Tool => Boolean(tool) && isToolLaunchReady(tool as Tool))
    .slice(0, limit);
}

export const categoryColors: Record<string, { bg: string; text: string; border: string; gradient: string; glow: string; from: string; to: string }> = {
  blue:    { bg: "bg-blue-500/10",    text: "text-blue-400",    border: "border-blue-500/20",    gradient: "rgba(84,120,166,0.16)",  glow: "rgba(84,120,166,0.18)",  from: "#5f86b8", to: "#456f9f" },
  violet:  { bg: "bg-violet-500/10",  text: "text-violet-400",  border: "border-violet-500/20",  gradient: "rgba(132,112,166,0.16)", glow: "rgba(132,112,166,0.18)", from: "#8d78ad", to: "#725f98" },
  green:   { bg: "bg-emerald-500/10", text: "text-emerald-400", border: "border-emerald-500/20", gradient: "rgba(72,145,104,0.16)",  glow: "rgba(72,145,104,0.18)",  from: "#57996f", to: "#3f7f5e" },
  orange:  { bg: "bg-orange-500/10",  text: "text-orange-400",  border: "border-orange-500/20",  gradient: "rgba(190,128,78,0.16)",  glow: "rgba(190,128,78,0.18)",  from: "#c58d5a", to: "#a86f43" },
  yellow:  { bg: "bg-yellow-500/10",  text: "text-yellow-400",  border: "border-yellow-500/20",  gradient: "rgba(178,151,73,0.16)",  glow: "rgba(178,151,73,0.18)",  from: "#bca65f", to: "#9d8949" },
  pink:    { bg: "bg-pink-500/10",    text: "text-pink-400",    border: "border-pink-500/20",    gradient: "rgba(184,104,139,0.16)", glow: "rgba(184,104,139,0.18)", from: "#bd7897", to: "#9e5f7d" },
  cyan:    { bg: "bg-cyan-500/10",    text: "text-cyan-400",    border: "border-cyan-500/20",    gradient: "rgba(76,151,164,0.16)",  glow: "rgba(76,151,164,0.18)",  from: "#5aa6b2", to: "#3f8794" },
  red:     { bg: "bg-red-500/10",     text: "text-red-400",     border: "border-red-500/20",     gradient: "rgba(184,89,82,0.16)",   glow: "rgba(184,89,82,0.18)",   from: "#b86d67", to: "#96524d" },
  teal:    { bg: "bg-teal-500/10",    text: "text-teal-400",    border: "border-teal-500/20",    gradient: "rgba(72,154,137,0.16)",  glow: "rgba(72,154,137,0.18)",  from: "#5aa996", to: "#438c7b" },
  indigo:  { bg: "bg-indigo-500/10",  text: "text-indigo-400",  border: "border-indigo-500/20",  gradient: "rgba(94,112,170,0.16)",  glow: "rgba(94,112,170,0.18)",  from: "#6d7ebb", to: "#5465a2" },
  amber:   { bg: "bg-amber-500/10",   text: "text-amber-400",   border: "border-amber-500/20",   gradient: "rgba(195,142,73,0.16)",  glow: "rgba(195,142,73,0.18)",  from: "#c99654", to: "#a9793d" },
  rose:    { bg: "bg-rose-500/10",    text: "text-rose-400",    border: "border-rose-500/20",    gradient: "rgba(187,92,103,0.16)",  glow: "rgba(187,92,103,0.18)",  from: "#bd6b76", to: "#9d535d" },
  sky:     { bg: "bg-sky-500/10",     text: "text-sky-400",     border: "border-sky-500/20",     gradient: "rgba(82,145,181,0.16)",  glow: "rgba(82,145,181,0.18)",  from: "#6198ba", to: "#477da0" },
  slate:   { bg: "bg-slate-500/10",   text: "text-slate-400",   border: "border-slate-500/20",   gradient: "rgba(100,116,139,0.16)",  glow: "rgba(100,116,139,0.18)",  from: "#7a8fa5", to: "#5f7489" },
};
