export const LANG_CODES = ["en", "ru", "es", "fr", "de", "pt", "zh", "ja", "ko", "ar", "hi", "tr"] as const;

export const STATIC_PAGES = [
  { path: "/", priority: "1.0", changefreq: "weekly" },
  { path: "/workflow", priority: "0.8", changefreq: "monthly" },
  { path: "/pricing", priority: "0.8", changefreq: "monthly" },
  { path: "/privacy", priority: "0.4", changefreq: "yearly" },
  { path: "/terms", priority: "0.4", changefreq: "yearly" },
  { path: "/contact", priority: "0.5", changefreq: "monthly" },
] as const;

export const TOOL_SLUGS = [
  "pdf-to-word",
  "pdf-to-jpg",
  "pdf-to-png",
  "pdf-to-text",
  "pdf-to-html",
  "pdf-to-excel",
  "word-to-pdf",
  "images-to-pdf",
  "excel-to-pdf",
  "text-to-pdf",
  "merge-pdf",
  "split-pdf",
  "rotate-pdf",
  "delete-pages",
  "reorder-pages",
  "extract-pages",
  "protect-pdf",
  "unlock-pdf",
  "sign-pdf",
  "watermark-pdf",
  "redact-pdf",
  "compress-pdf",
  "ocr-pdf",
  "photo-to-pdf",
  "pdf-page-numbers",
  "pdf-header-footer",
  "bates-numbering",
  "edit-pdf",
  "crop-pdf",
  "extract-images",
  "pdf-metadata",
  "compare-pdf",
  "remove-blank-pages",
  "resize-pages",
  "grayscale-pdf",
  "pdf-bookmarks",
  "sanitize-pdf",
  "extract-forms",
  "pdf-to-pdfa",
  "add-blank-pages",
  "repair-pdf",
  "flatten-pdf",
  "auto-redact",
  "n-up-pdf",
  "split-by-size",
  "overlay-pdf",
  "invert-colors",
  "to-single-page",
  "remove-images",
  "form-fill",
  "split-by-chapters",
  "booklet-imposition",
  "scanner-effect",
  "pdf-to-markdown",
  "add-background",
  "pdf-diff",
  "pdf-to-audio",
  "pdf-to-pptx",
] as const;

export type ToolSlug = typeof TOOL_SLUGS[number];
